-- MySQL Script generated by MySQL Workbench
-- Sat May  9 19:14:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema totalfit_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema totalfit_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `totalfit_dev` DEFAULT CHARACTER SET utf8 ;
USE `totalfit_dev` ;

-- -----------------------------------------------------
-- Table `totalfit_dev`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`Company` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`Company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `address` VARCHAR(150) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`Person` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`Person` (
  `identification` VARCHAR(9) NOT NULL,
  `first_name` VARCHAR(90) NOT NULL,
  `last_name` VARCHAR(90) NOT NULL,
  `birth_date` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`identification`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`Employee` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`Employee` (
  `identification` VARCHAR(9) NOT NULL,
  `company_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`identification`, `company_id`),
  INDEX `fk_Employee_Company_idx` (`company_id` ASC) VISIBLE,
  INDEX `fk_Employee_Person1_idx` (`identification` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Company`
    FOREIGN KEY (`company_id`)
    REFERENCES `totalfit_dev`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Person1`
    FOREIGN KEY (`identification`)
    REFERENCES `totalfit_dev`.`Person` (`identification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`Exercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`Exercise` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`Exercise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`CompanyExercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`CompanyExercise` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`CompanyExercise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `exercise_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `machine` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  INDEX `fk_CompanyExercise_Company1_idx` (`company_id` ASC) VISIBLE,
  INDEX `fk_CompanyExercise_Exercise1_idx` (`exercise_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_CompanyExercise_Company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `totalfit_dev`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CompanyExercise_Exercise1`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `totalfit_dev`.`Exercise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`RoutineTemplate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`RoutineTemplate` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`RoutineTemplate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `employee_identification` VARCHAR(9) NOT NULL,
  `company_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_RoutineTemplate_Employee1_idx` (`employee_identification` ASC, `company_id` ASC) VISIBLE,
  CONSTRAINT `fk_RoutineTemplate_Employee1`
    FOREIGN KEY (`employee_identification` , `company_id`)
    REFERENCES `totalfit_dev`.`Employee` (`identification` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`RoutineTemplateExercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`RoutineTemplateExercise` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`RoutineTemplateExercise` (
  `routine_template_id` INT NOT NULL,
  `company_exercise_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `udated_at` DATETIME NOT NULL DEFAULT NOW(),
  INDEX `fk_RoutineTemplateExercise_RoutineTemplate1_idx` (`routine_template_id` ASC) VISIBLE,
  INDEX `fk_RoutineTemplateExercise_CompanyExercise1_idx` (`company_exercise_id` ASC) VISIBLE,
  PRIMARY KEY (`routine_template_id`, `company_exercise_id`),
  CONSTRAINT `fk_RoutineTemplateExercise_RoutineTemplate1`
    FOREIGN KEY (`routine_template_id`)
    REFERENCES `totalfit_dev`.`RoutineTemplate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RoutineTemplateExercise_CompanyExercise1`
    FOREIGN KEY (`company_exercise_id`)
    REFERENCES `totalfit_dev`.`CompanyExercise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`Client` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`Client` (
  `identification` VARCHAR(9) NOT NULL,
  `company_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`identification`, `company_id`),
  INDEX `fk_Client_Company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Person1`
    FOREIGN KEY (`identification`)
    REFERENCES `totalfit_dev`.`Person` (`identification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `totalfit_dev`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`Review` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`Review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_identification` VARCHAR(9) NOT NULL,
  `client_company_id` INT NOT NULL,
  `fat` FLOAT NOT NULL,
  `muscle` FLOAT NOT NULL,
  `water` FLOAT NOT NULL,
  `height` FLOAT NOT NULL,
  `weight` FLOAT NOT NULL,
  `appointment_date` DATETIME NOT NULL,
  `employee_identification` VARCHAR(9) NULL,
  `employee_company_id` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_Review_Client1_idx` (`client_identification` ASC, `client_company_id` ASC) VISIBLE,
  INDEX `fk_Review_Employee1_idx` (`employee_identification` ASC, `employee_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Review_Client1`
    FOREIGN KEY (`client_identification` , `client_company_id`)
    REFERENCES `totalfit_dev`.`Client` (`identification` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_Employee1`
    FOREIGN KEY (`employee_identification` , `employee_company_id`)
    REFERENCES `totalfit_dev`.`Employee` (`identification` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`RoutineFocus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`RoutineFocus` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`RoutineFocus` (
  `name` NVARCHAR(50) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`Routine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`Routine` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`Routine` (
  `review_id` INT NOT NULL,
  `number_weeks` INT NOT NULL,
  `number_routines` INT NOT NULL,
  `focus` NVARCHAR(50) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  INDEX `fk_Routine_Review1_idx` (`review_id` ASC) VISIBLE,
  INDEX `fk_Routine_RoutineFocus1_idx` (`focus` ASC) VISIBLE,
  PRIMARY KEY (`review_id`),
  CONSTRAINT `fk_Routine_Review1`
    FOREIGN KEY (`review_id`)
    REFERENCES `totalfit_dev`.`Review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Routine_RoutineFocus1`
    FOREIGN KEY (`focus`)
    REFERENCES `totalfit_dev`.`RoutineFocus` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`RoutineDay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`RoutineDay` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`RoutineDay` (
  `review_id` INT NOT NULL,
  `day_number` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`review_id`, `day_number`),
  CONSTRAINT `fk_RoutineDay_Routine1`
    FOREIGN KEY (`review_id`)
    REFERENCES `totalfit_dev`.`Routine` (`review_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`RoutineDayExercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`RoutineDayExercise` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`RoutineDayExercise` (
  `review_id` INT NOT NULL,
  `day_number` INT NOT NULL,
  `company_exercise_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`review_id`, `day_number`, `company_exercise_id`),
  INDEX `fk_RoutineDayExercise_CompanyExercise1_idx` (`company_exercise_id` ASC) VISIBLE,
  CONSTRAINT `fk_RoutineDayExercise_RoutineDay1`
    FOREIGN KEY (`review_id` , `day_number`)
    REFERENCES `totalfit_dev`.`RoutineDay` (`review_id` , `day_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RoutineDayExercise_CompanyExercise1`
    FOREIGN KEY (`company_exercise_id`)
    REFERENCES `totalfit_dev`.`CompanyExercise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`RoutineDayExerciseDescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`RoutineDayExerciseDescription` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`RoutineDayExerciseDescription` (
  `review_id` INT NOT NULL,
  `day_number` INT NOT NULL,
  `company_exercise_id` INT NOT NULL,
  `week_nbr` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`review_id`, `day_number`, `company_exercise_id`, `week_nbr`),
  CONSTRAINT `fk_RoutineDayExerciseDescription_RoutineDayExercise1`
    FOREIGN KEY (`review_id` , `day_number` , `company_exercise_id`)
    REFERENCES `totalfit_dev`.`RoutineDayExercise` (`review_id` , `day_number` , `company_exercise_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalfit_dev`.`CompanyClass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `totalfit_dev`.`CompanyClass` ;

CREATE TABLE IF NOT EXISTS `totalfit_dev`.`CompanyClass` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_identification` VARCHAR(9) NOT NULL,
  `company_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `minutes_length` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_CompanyClass_Employee1_idx` (`employee_identification` ASC, `company_id` ASC) VISIBLE,
  CONSTRAINT `fk_CompanyClass_Employee1`
    FOREIGN KEY (`employee_identification` , `company_id`)
    REFERENCES `totalfit_dev`.`Employee` (`identification` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
